spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tLsUCRYX5Ugr6qHy3Ez
      secret-key: 3RaYvoiN7IxhBZL5Tw7f6eGoBa4I8z
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimail-air
  application:
    name: gulimail-third-party

server:
  port: 30000